add draft to the types of content that need it
mitodl/ocw-hugo-projects pull request #125
Opened 2022-02-16 22:48 UTC by gumaerc

#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-studio/issues/933

#### What's this PR do?
This PR adds a boolean `draft` field to items in the `Content` category in both the `ocw-www` and `ocw-course` starter configurations, defaulting to false.  When set to true, this will automatically set `draft: true` in the front matter of any content being published, telling Hugo to not render the page or any JSON data.

#### How should this be manually tested?
 - Spin up a local instance of [`ocw-studio`](https://github.com/mitodl/ocw-studio), making sure you follow the instructions to set up your own Github organization for testing
 - Create the `ocw-www` and `ocw-course` starters if you don't have them already and update their configuration with the ones from this branch
 - Create a test site or open an existing one
 - Create two test pages, one with `draft` set to `false`, and the other with `draft` set to `true`
 - Publish the site to your test org and then clone the output
 - Clone `ocw-hugo-themes` if you don't have it already and set it up to spin up your test site locally
 - Spin up the test site and verify that your page with `draft: true` is not reachable, but your page with `draft: false` is

2022-02-16 22:53 UTC, pdpinch commented
Do we need to set it to default to False? Will is be set to false for existing content in studio?

2022-02-17 10:18 UTC, MAbdurrehman12 commented
> Do we need to set it to default to False? Will it be set to false for existing content in studio?

I guess, by default, it is set to `false`

2022-02-17 10:49 UTC, MAbdurrehman12 requested changes
Looks great! 
However, I noticed a couple of things: (not sure if something is wrong at my end)

1- I created 2 pages, page 1 with `draft: on` and page 2 with `draft: off`, built the course and it looked good as the `page 1`, with `draft: on`, was not showing, then I set `draft: off` for page 1 and it started showing correctly, then again, I set its `draft: on`, and now it's showing whereas it should not show, as it has `draft: on`.

I repeated this for a couple of pages: 
draft: `on`, then `off` and then again `on`, and the page shows up even with `draft: on`.
Not sure if I'm doing something wrong. 

2- If we create a page with `draft: on` and add it's navigation menu item, then don't we also need to hide the menu item? as currently, for pages, having `draft: on`, their menu item is also showing and upon clicking, we have a `404` page.  

3- I don't think this is really important but from a UX perspective, will the user be interested in knowing which pages are draft and which are not, by only seeing the pages list? 
for now, If we have a list of pages then in order to know which page is draft and which is not, we have to open it
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/93309234/154459379-6d641c89-fd1c-4bd0-b84e-4daeecae4c0a.png">
maybe we can show a draft label in this list.

ps: I haven't tested resources, video gallery etc as i guess they will have the same behaviour and please correct me if I'm wrong in any of the above point.

2022-02-17 14:09 UTC, alicewriteswrongs commented
@MAbdurrehman12 I think you are touching on a bit of a product question, which has a technical component. @gumaerc is probably best positioned to answer whether a page disappearing from build `n+1` (if it was present in build `n`) will get removed from the CDN properly. But on the product side, I'm wondering if we need to support changing already published content back to draft? I can see the use-case if something was published accidentally, but then maybe it's more clear to have an 'unpublish' action that we can use to specifically trigger any cache purging we need to do. Idk, just chiming in a little bit here!

2022-02-17 15:32 UTC, gumaerc commented
Also to answer @pdpinch 's question, it is set to false by default as that is the default for boolean fields.  For existing content, they will simply not set the value which is the equivalent of it being set to false.

2022-02-17 15:39 UTC, Ferdi commented
* I think the terminology here should be publish / unpublished,   instead of draft.    "Draft" would be appropriate for the use case when I have published a page,  I want to make some changes to it, but not ready to publish those  *changes* yet.  
* It's the responsibility of the content editor to try not to reference pages that are unpublished.  There is no clean way to do that. Or , out of scope for this ticket
* It'd be great to have an indicator in the studio UI about the status of the post . Can you open an issue ?

2022-02-17 18:33 UTC, gumaerc commented
@Ferdi We can change the label from "Draft" to something else, but the front matter key still needs to be `draft` with a value of true or false.  If we change the label to "Published" then the boolean would have the opposite meaning, because setting it to true would set `draft: true`.  The label should be analogous with the state of a page being a draft.  I think it makes sense to leave this terminology as "draft" and call previewing the site "preview."  If we wanted to label this setting "Published" then we would need some additional logic in `ocw-studio` that would flip the boolean and set the `draft` front matter key to that.

2022-02-18 07:52 UTC, MAbdurrehman12 commented
@alicewriteswrongs You're right. Thanks for your input

@gumaerc Thanks for the explanation, I thought that the public folder is completely overridden every time we run `npm run start:course` but it initially generated those pages which were rendering again, so deleting the public directory resolves this issue. The rest of the things you mentioned for `ocw-studio` should be considered I guess.

@Ferdi 
> publish / unpublished, instead of draft 

Carey has shared his thoughts on this.
> It's the responsibility of the content editor to try not to reference pages that are unpublished 

I guess we can also handle this in `ocw-studio` in another ticket but not sure how important and valuable this is for now.

> It'd be great to have an indicator in the studio UI about the status of the post . Can you open an issue ?

Sure, I'll open an issue for this.

2022-02-23 02:32 UTC, Ferdi commented
> If we change the label to "Published" then the boolean would have the opposite meaning, because setting it to true would set draft: true.

@gumaerc good point !

2022-02-24 21:27 UTC, gumaerc commented
@Ferdi @pdpinch @MAbdurrehman12 is this good to merge now?

2022-02-24 21:31 UTC, pdpinch commented
I think its fine. Is the follow up to allow publishing draft content to the staging server ready to go?

2022-02-25 07:07 UTC, MAbdurrehman12 approved these changes
👍

2022-03-01 21:57 UTC, merged