feat: embed resource added for ocw www
mitodl/ocw-hugo-projects pull request #161
Opened 2022-04-19 19:41 UTC by MAbdurrehman12

#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-hugo-projects/issues/160

#### What's this PR do?
- Adds `resource embed` in ocw-www studio config 

#### How should this be manually tested?
- Checkout this branch
- Copy the config
- Either in studio RC or in studio local setup, paste this config in the starter of `ocw-www`
- Go to `ocw-www` in `studio/sites` and add/edit a page 
- Verify that `Embed Resource` button is now there in editor

#### Screenshots (if appropriate)
<img width="870" alt="image" src="https://user-images.githubusercontent.com/93309234/164082726-8a3bd49b-2299-4790-8b94-e7dfd77f5304.png">

<img width="745" alt="image" src="https://user-images.githubusercontent.com/93309234/164082753-1c88a2c2-30b8-489d-a1ec-87d27af3a293.png">

2022-04-19 19:48 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +          - resource
This will show the embed resource button and pop-up but in order to view and select any resource from the pop-up, I think, we will have to change the `filetype` to `resourcetype` [here](https://github.com/mitodl/ocw-hugo-projects/blob/c2d92174be8e63e6c169127a68e5381e4625b906/ocw-www/ocw-studio.yaml#L251). 
As resources with `name: filetype` does not populate in the embed resource pop-up but changing that to `name: resourcetype` does the job and populates the resources. I'm just a bit unsure about the impact or side-effect (if any) it will have, so reviewer can share their thoughts

2022-04-20 13:12 UTC, pdpinch commented on ocw-www/ocw-studio.yaml
> +          - resource
Is that how it is set in ocw-course.yaml? 

Does this mean we will need a content migration in studio as well, for existing resources in sites using the ocw-www starter? (there's only one site, and not too many resources, so we could conceivably do it by hand)

2022-04-20 14:07 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +          - resource
> Is that how it is set in ocw-course.yaml?

Yes. In `ocw-course/ocw-studio.yaml` we have `name: resourcetype` for resources.

> there's only one site, and not too many resources, so we could conceivably do it by hand

I agree.

2022-04-21 07:10 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +          - resource
@pdpinch Shall we make this change then?

2022-04-22 14:15 UTC, gumaerc requested changes
Looks good, I think we're just missing one thing:

2022-04-22 14:15 UTC, gumaerc commented on ocw-www/ocw-studio.yaml
> +        embed:
Can we also add:

```
        link:
          - resource
          - page
```

The `embed` tag only allows inline embedding of resources like images or videos, the `link` tag is required for linking to other pages or resources, and I have a feeling we want that too.  Can you confirm @pdpinch ?

2022-04-22 14:17 UTC, gumaerc commented on ocw-www/ocw-studio.yaml
> +          - resource
@pdpinch I'm not sure why we would need a migration here.  These are properties that are read from the starter when initializing the markdown body editor, and this change will simply allow resource linking / embedding on pages in `ocw-www`.  What would we be migrating?

2022-04-22 14:54 UTC, pdpinch commented on ocw-www/ocw-studio.yaml
> +        embed:
Yes. This should be the same for ocw-www and for ocw-course

2022-04-22 14:55 UTC, pdpinch commented on ocw-www/ocw-studio.yaml
> +          - resource
Ah, I see.  I didn't realize this was only for configuring the UI. No migration needed.

2022-04-22 15:17 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +        embed:
We already have `course_collections` and `resource_collections` in link and after adding `resource` and `page`
<img width="223" alt="image" src="https://user-images.githubusercontent.com/93309234/164743951-ed1995d6-a847-44c0-ac87-4732bf28e498.png">

we have something like this. The UI doesn't looks much good but I think it can be improved later on in a separate PR
<img width="645" alt="image" src="https://user-images.githubusercontent.com/93309234/164743911-e57df069-7d8b-4882-9d5e-ba7aff28b955.png">

2022-04-22 15:23 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +          - resource
Sorry, I think I also misread it.
but after changing `name: filetype` to `name: resourcetype`,  I think we will have to update the existing resources.

2022-04-22 15:30 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +        name: resourcetype
This [comment](https://github.com/mitodl/ocw-hugo-projects/pull/161#discussion_r853430755) stating why this name has been changed

2022-04-22 15:47 UTC, pdpinch commented on ocw-www/ocw-studio.yaml
> +        embed:
@ChristopherChudzicki what are your thoughts on this?

If we want to combine some of those buttons, would it require an API change?

2022-04-22 18:54 UTC, ChristopherChudzicki commented on ocw-www/ocw-studio.yaml
> +          - resource
> I think, we will have to change the filetype to resourcetype [here](https://github.com/mitodl/ocw-hugo-projects/blob/c2d92174be8e63e6c169127a68e5381e4625b906/ocw-www/ocw-studio.yaml#L251).

Agree. BTW: There are a few other places in the config that reference `filetype`. Those probably need to be updated, too.

> name: filetype to name: resourcetype, I think we will have to update the existing resources.

Agree... There are 52 resources right now in ocw-www. They would not function properly on the frontend (of studio) without the migration.

2022-04-22 18:58 UTC, ChristopherChudzicki commented on ocw-www/ocw-studio.yaml
> +          - page
**Requested Change:**

I can double check this a bit later, but I am pretty we will need to change `pages` to `page` [here](https://github.com/mitodl/ocw-hugo-projects/pull/161/files#diff-67d56cdef4a18dc49e4d82b9f19d3ebc72b4515dabde4f81a4e73ab1eb0e8c47R7) ...Another quirky difference (like filetype vs resourcetype) between the current www and course configs.

It will be really nice to have brought these configs more in-line!

2022-04-22 18:59 UTC, ChristopherChudzicki requested changes

2022-04-22 18:59 UTC, ChristopherChudzicki commented on ocw-www/ocw-studio.yaml
> +          - page
**Requested Change:**

I can double check this a bit later, but I am pretty we will need to change `pages` to `page` [here](https://github.com/mitodl/ocw-hugo-projects/pull/161/files#diff-67d56cdef4a18dc49e4d82b9f19d3ebc72b4515dabde4f81a4e73ab1eb0e8c47R7) ...Another quirky difference (like filetype vs resourcetype) between the current www and course configs.

It will be really nice to have brought these configs more in-line!

2022-04-22 19:05 UTC, ChristopherChudzicki commented on ocw-www/ocw-studio.yaml
> +        embed:
@pdpinch Something like this? I don't think we'll need any API changes for that. ![](https://user-images.githubusercontent.com/9010790/155206117-d5681d5b-4dec-488b-aad4-a220c68bff10.png)

The code for that screenshot was briefly in studio master (from [studio PR 1048]( https://github.com/mitodl/ocw-studio/pull/1048) ... We ended up removing that functionality in [studio PR 1055](https://github.com/mitodl/ocw-studio/pull/1055) because 
> Why only link collections in ocw-www? Because linking to collections in ocw-www sites is the immediate need and ... right now there are some mismatches between ocw-course and ocw-www configurations which would make linking to other things (pages, resources) a bit annoying. For example, in courses, pages have type=page, but in www they have type=pages. And in courses, resource types are determined by resourcename but in www they are determined by filename.

But that's the issue that @MAbdurrehman12 is fixing here! So we should be able to restore the dropdown fairly easily.

2022-04-24 20:01 UTC, pdpinch commented on ocw-www/ocw-studio.yaml
> +          - page
Can/should this (changing `pages` to `page` be a separate PR?

2022-04-24 20:48 UTC, ChristopherChudzicki commented on ocw-www/ocw-studio.yaml
> +          - page
As it currently stands, the resource picker will show a Pages tab but the pages tab will always be empty:

<img width="744" alt="Screen Shot 2022-04-24 at 4 43 18 PM" src="https://user-images.githubusercontent.com/9010790/164995852-7936b231-276a-4cd1-888d-419050935b9d.png">

I think doing the "pages" portion in a separate PR is totally reasonable, but we might want to remove "page" from the link list until then so that the empty tab doesn't show up.

2022-04-25 00:48 UTC, pdpinch commented on ocw-www/ocw-studio.yaml
> +        embed:
that's a bit out of scope for the issue, but my expectation is that we could add links to resources as well. It's up to @MAbdurrehman12 whether to add it to this PR, or open a separate one for resource links.

2022-04-25 06:44 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +        embed:
@ChristopherChudzicki This layout looks great!

2022-04-25 08:29 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +    label: Pages
Label changed to `pages` just to maintain better consistency with `ocw-course/ocw-studio.yaml`

2022-04-25 08:45 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +          - page
Thanks for pointing this out @ChristopherChudzicki.
@gumaerc @pdpinch 
I have made the following changes to this PR: 
1. Updated `pages` to `page`. Now pages are being shown when adding a link: 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/93309234/165052489-54c518f9-ef13-4ac9-9442-1cbd7031b21b.png">

2. Updated all the configs to reference `resourcetype` which were previously referencing `filetype` and tested this change. It works as expected.

and I think yes, we will need a migration, to update all the resources of `ocw-www`. (i.e: Change `filetype` to `resourcetype` in metadata.)

Is there anything else or anything I missed?

2022-04-25 18:40 UTC, gumaerc commented on ocw-www/ocw-studio.yaml
> +          - page
@ChristopherChudzicki @MAbdurrehman12 You guys are right, a migration will be necessary when it comes to moving `filetype` to `resourcetype`.  I didn't notice this particular change when I made my previous comment and was referring to the fact that simply adding new `embed` or `link` directives doesn't necessitate a migration.  I just tested this out locally and everything looks good to me.

2022-04-25 20:21 UTC, MAbdurrehman12 commented on ocw-www/ocw-studio.yaml
> +          - page
Thanks, @gumaerc, can you approve the PR if everything looks good?
@ChristopherChudzicki Would you like to have a look too?

2022-04-25 20:26 UTC, ChristopherChudzicki commented on ocw-www/ocw-studio.yaml
> +          - page
@MAbdurrehman12 Oops, I thought I approved this earlier today. My bad!

2022-04-25 20:27 UTC, ChristopherChudzicki approved these changes

2022-04-25 20:49 UTC, gumaerc commented
@MAbdurrehman12 Something @Ferdi pointed out to me is that we should also allow linking to the other types of `ocw-www` specific content like testimonials, promos, etc.

2022-04-25 21:26 UTC, MAbdurrehman12 commented
> @MAbdurrehman12 Something @Ferdi pointed out to me is that we should also allow linking to the other types of `ocw-www` specific content like testimonials, promos, etc.

Sure, which should be included?  (testimonials, promos, stories, instructors?)

2022-04-25 22:28 UTC, gumaerc commented
@MAbdurrehman12 I'd say all of them aside from instructors.  Instructors don't have an HTML template in the theme, they only have a JSON template to expose that data via the static JSON API.

2022-04-26 15:29 UTC, Ferdi commented
I suggest we should try to merge this PR soon and make improvements in subsequent PRs

2022-04-26 15:35 UTC, gumaerc approved these changes
@MAbdurrehman12 As Ferdi says, I think we should merge this PR and make further improvements in another PR as this is getting a bit out of scope.

2022-04-26 15:48 UTC, merged