Add instructor collection
mitodl/ocw-hugo-projects pull request #17
Opened 2021-07-14 15:23 UTC by noisecapella

Fixes #14

2021-07-14 15:38 UTC, Ferdi commented
I think our plan for now is to just reference the instructors from site metadata.  We probably don't want to publish the instructors list  or individual pages in the website. it seems like  if you say "headless=true", hugo wont publish that particular page. Similar to what we do with notifications https://github.com/mitodl/ocw-hugo-projects/blob/main/ocw-www/ocw-studio.yaml#L68 /cc @gumaerc

2021-07-16 17:09 UTC, noisecapella commented on ocw-www/ocw-studio.yaml
> +      - label: Full name (incl salutation)
Not sure whether it makes sense to use `Title` for this instead since it already shows up in the UI

2021-07-16 21:49 UTC, gumaerc reviewed
These are valid changes to the studio config but I have a couple questions.  I think mostly I'm just missing some context and could use some help understanding some things:

2021-07-16 21:49 UTC, gumaerc commented on ocw-www/ocw-studio.yaml
> +  - category: Content
I'm probably missing some context here, but why does this need to be a part of `ocw-www`?  Are we going to be referencing instructors outside of course pages?

2021-07-16 21:49 UTC, gumaerc commented on ocw-www/ocw-studio.yaml
> +      - label: Full name (incl salutation)
Why wouldn't this field be composed out of the other components that make it up?  Is the idea that we want to be able to have a "manual override" of sorts in case we need the display name to be different?

2021-07-16 21:49 UTC, gumaerc commented on ocw-course/ocw-studio.yaml
> +      - file: data/metadata.json
Moving forward, will we be storing the course metadata in `metadata.json` or `course.json`?  It doesn't really matter either way, but if we do decide to use `metadata.json` there will need to be a corresponding update to `ocw-hugo-themes` and `ocw-to-hugo` to preserve compatibility.

2021-07-19 13:28 UTC, noisecapella commented on ocw-www/ocw-studio.yaml
> +      - label: Full name (incl salutation)
I think it should be composed of other components but I don't think we have a way to do that right now. The `RelationField` only has a `display_field` property which points to the field to be shown

2021-07-19 13:42 UTC, noisecapella commented on ocw-www/ocw-studio.yaml
> +  - category: Content
It's part of the requirement for this issue that there is a global list of instructors that course authors pick from. But I think it also makes sense intuitively to do it this way. If instructors were `WebsiteContent` of the course `Website`, when creating a new course you would create each instructor manually and then add all of the instructors which you created in the course metadata. If they are owned by `ocw-www` then you could select from that list with a `RelationField`

2021-07-19 13:43 UTC, noisecapella commented on ocw-course/ocw-studio.yaml
> +      - file: data/metadata.json
I think I just picked this based on what we used in example site metadata yaml previously. I'll change to `course.json`

2021-07-19 16:06 UTC, noisecapella commented on ocw-www/ocw-studio.yaml
> +      - label: Full name (incl salutation)
@gumaerc FYI Ferdi told me we should use Title instead so I removed this

2021-07-19 17:05 UTC, gumaerc requested changes
Just one last change and this should be good to go:

2021-07-19 17:05 UTC, gumaerc commented on ocw-course/ocw-studio.yaml
> +            display_field: display_name
I think this needs to be `title`

2021-07-20 13:40 UTC, gumaerc approved these changes
👍

2021-07-20 17:46 UTC, merged