fix: we did not add a metadata_keywords field to pages
mitodl/ocw-hugo-projects pull request #195
Opened 2022-06-10 21:09 UTC by pdpinch

#### What are the relevant tickets?

no issue, I just noticed that the release notes were misleading

#### What's this PR do?

Corrects the release notes to remove "add ... metadata_keywords fields to pages"

#### How should this be manually tested?

I hope this doesn't mess up Doof too much.

2022-06-10 21:09 UTC, pdpinch commented
@gumaerc when you get a chance?

2022-06-10 21:19 UTC, gumaerc requested changes

2022-06-10 21:19 UTC, gumaerc commented on RELEASE.rst
> +- add metadata_description field to pages (#190)
Good catch, and in addition to this the field is simply called `description` per Ferdi's recommendation

2022-06-14 21:24 UTC, pdpinch commented on RELEASE.rst
> +- add metadata_description field to pages (#190)
updated!

2022-06-15 22:12 UTC, gumaerc approved these changes
:+1:

2022-06-17 12:28 UTC, merged