Added config for resource bundle
mitodl/ocw-hugo-projects pull request #198
Opened 2022-06-17 12:28 UTC by Wassaf-Shahzad

#### Pre-Flight checklist

- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #196 

#### What's this PR do?
Adds a configuration for resource bundle.

#### How should this be manually tested?
- Use this configuration in studio and verify resource bundle can be created.

2022-06-17 18:09 UTC, gumaerc approved these changes
:+1: 

This looks good, but I would wait to merge this until an `ocw-hugo-themes` PR has been made to add a layout to display these resources.  If we merge this and people start creating resource bundles, Hugo will attempt to render them in site builds and likely end up rendering blank pages.  When Hugo doesn't find a layout for a particular kind of content it will fall back to a default layout.  In this case I believe it would be `base-theme/layouts/_default/single.html` which is simply:

```
{{ define "main" }}
{{ .Content }}
{{ end }}
```

Since these pages have no markdown content and are entirely a metadata list of resources, this would result in a blank page.  Since Hugo would still recognize these as `Page` objects, the links would render into the sitemap and also be indexed by Google.  There's no harm in adding the layout first, as that just makes it available for use in the theme and it won't actually be used until sites start generating content that utilizes it.

2022-06-20 07:10 UTC, Wassaf-Shahzad commented
> 👍
> 
> This looks good, but I would wait to merge this until an `ocw-hugo-themes` PR has been made to add a layout to display these resources. If we merge this and people start creating resource bundles, Hugo will attempt to render them in site builds and likely end up rendering blank pages. When Hugo doesn't find a layout for a particular kind of content it will fall back to a default layout. In this case I believe it would be `base-theme/layouts/_default/single.html` which is simply:
> 
> ```
> {{ define "main" }}
> {{ .Content }}
> {{ end }}
> ```
> 
> Since these pages have no markdown content and are entirely a metadata list of resources, this would result in a blank page. Since Hugo would still recognize these as `Page` objects, the links would render into the sitemap and also be indexed by Google. There's no harm in adding the layout first, as that just makes it available for use in the theme and it won't actually be used until sites start generating content that utilizes it.

Yeah no problem. I just added config first since I wanted to to see how the .md files would be produces before committing to designing the theme.

2022-06-22 20:20 UTC, Ferdi commented on ocw-course/ocw-studio.yaml
> +    label: "Resource Bundles"
`label: "Resource lists`

2022-06-22 20:21 UTC, Ferdi commented on ocw-course/ocw-studio.yaml
> +    name: "resource_bundle"
`name: "resource-list"`

2022-06-23 13:40 UTC, Ferdi commented
@Wassaf-Shahzad Can we wrap this up ?

2022-06-27 12:24 UTC, Wassaf-Shahzad commented
> @Wassaf-Shahzad Can we wrap this up ?

Yes, The PR blocking this PR was merged on Friday and this PR is ready to go

2022-06-27 22:09 UTC, gumaerc requested changes
I have a couple questions based on Ferdi's changes:

2022-06-27 22:09 UTC, gumaerc commented on ocw-course/ocw-studio.yaml
> +          - resource_bundle
Should this be `resource_list`?

2022-06-27 22:09 UTC, gumaerc commented on ocw-course/ocw-studio.yaml
> +    folder: content/lists
@Ferdi This is a bit generic of a name, no?  Is the idea here that we want to have one layout for multiple types of these lists in the theme?  Either way, we should merge a PR adding a layout at `course/layouts/lists/single.html` if we're going to use this folder.  As a reminder, Hugo selects a layout to use based primarily on the folder the content is placed in.  Right now we have `course/layouts/course-lists/single.html`.  I don't want to assume too much before you respond to this, but as this is, if we merge this PR then people will be able to create content for which a layout does not yet exist in the theme.

2022-06-27 22:54 UTC, gumaerc commented on ocw-course/ocw-studio.yaml
> +    name: "resource-lists"
This should be `resource-list` not `resource-lists` as it will determine the `type` property when creating `WebsiteContent` objects in Studio.

2022-06-27 22:57 UTC, Ferdi commented on ocw-course/ocw-studio.yaml
> +    folder: content/lists
We had a brief discussion about this here https://github.com/mitodl/hq/discussions/93#discussioncomment-3003913

2022-06-28 06:52 UTC, Wassaf-Shahzad commented on ocw-course/ocw-studio.yaml
> +    name: "resource-lists"
Thanks for the needed context, I was wondering what the name property does. Done

2022-06-28 15:16 UTC, gumaerc requested changes
This just needs one last change then it's good to go:

2022-06-28 15:16 UTC, gumaerc commented on ocw-course/ocw-studio.yaml
> +          - resource_list
This needs to be `resource-list` to match the `name` property.  When studio is looking at this to determine what can be linked to in CKEditor, it matches based on the `type` property of the `WebsiteContent` object, which is set by the `name` of the collection.  We should standardize on either underscores or dashes, but that's an issue for another PR.

2022-06-28 15:18 UTC, gumaerc commented on ocw-course/ocw-studio.yaml
> +          - resource_list
I think that `name` on collections should also probably just be `type` instead, but that's also a separate issue.

2022-06-28 17:50 UTC, Wassaf-Shahzad commented on ocw-course/ocw-studio.yaml
> +          - resource_list
Sorry, Done

2022-06-28 18:39 UTC, gumaerc approved these changes
:+1:

2022-06-29 07:30 UTC, merged