feat: create a new link type (collection)
mitodl/ocw-hugo-projects pull request #271
Opened 2024-01-15 11:22 UTC by HussainTaj-arbisoft

### What are the relevant tickets?
Closes https://github.com/mitodl/hq/issues/3359

### Description (What does it do?)

This PR creates a new collection called Links. The entities in this collection will represent our external links.

### Screenshots (if appropriate):

<img width="1641" alt="Screenshot 2024-01-15 at 4 20 20 PM" src="https://github.com/mitodl/ocw-hugo-projects/assets/71316217/64a6b662-4a10-40cc-a876-c4999ce80cdc">

### How can this be tested?

### Checklist:
- [ ] New shortcode functionality is merged.

2024-01-22 13:34 UTC, pdpinch requested changes
I know this is just a draft, but I had some questions & comments.

2024-01-22 13:34 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +        help: Text to display as the link.
Do we need Title and Text?

2024-01-22 13:34 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +        name: external_url
Why `external_url` and not just `url`? 

Does this reflect the intent that the URL should not be in the same domain as the published site, for example, ocw.mit.edu? Will we do anything to validate that? 

If we don't want URLs within the same domain, do we have a reliable mechanism to link to all other pages and resources within the domain?

2024-01-22 13:34 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +        help: The URL. For example, https://ocw.mit.edu/
This is a confusing example. 

```suggestion
        help: The URL. For example, https://raise.mit.edu/ or https://owl.english.purdue.edu/owl/resource/747/01/ 
```

2024-01-22 13:34 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +          - label: CC-BY-NC-SA
There shouldn't be a dash between the CC and the rest of the string. This is an error in our existing project & data. 

```suggestion
          - label: CC BY-NC-SA
```

See https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en

2024-01-22 13:34 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +          - label: CC-BY-NC
```suggestion
          - label: CC BY-NC
```

2024-01-22 13:34 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +          - label: CC-BY
```suggestion
          - label: CC BY
```

2024-01-22 13:34 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +          embeds.
Can you give me an example of where this is used?

Also, can you remind me of the effect of setting `widget: hidden`? Does that mean that studio users won't be able to edit this link?

2024-01-22 13:34 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +        required: false
What does this mean?

2024-01-23 07:45 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +        help: Text to display as the link.
The title field is required for all content types. It is generally used as the title of the page. In addition to that, `text` can be formatted while `title` is generally unformatted.

In most cases, these fields are redundant. I'm currently experimenting with the idea of using `title` for both purposes.

2024-01-23 07:49 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +        name: external_url
Hugo has a specific meaning for the `url` [front matter](https://gohugo.io/content-management/front-matter/). We can't name our meta field that.

This has nothing to do with domains. Any text can be used inside this field. If I remember correctly, Studio doesn't have URI field validations either.

2024-01-23 07:51 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +        required: false
This field indicates whether the original link is no longer functioning.

This meta field will be used to decide between rendering `external_url` and `backup_url`.

This can be renamed to `is_broken`.

2024-01-23 08:16 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +          embeds.
> Also, can you remind me of the effect of setting widget: hidden? 

`widget:hidden` hides the `is_image` field from the user, while still tracking it in our database.

> Does that mean that studio users won't be able to edit this link?

They won't be able to edit this specific field. They will be able to edit fields that are visible to them.

2024-01-23 15:00 UTC, ChristopherChudzicki commented on ocw-course-v2/ocw-studio.yaml
> +        help: Text to display as the link.
Do we need either? (_Aside from `title` being required, which seems like a technical limitation._)

What I mean is... If two links have the same URL but different text, are they two separate WebsiteContent objects?
- `[github](https://github.com)`
- `[github homepage](https://github.com)`

These could be the same content object but differ in the Hugo shortcode:
```
{{< external_link title="github" uuid="whatever-id" >}}
{{< external_link title="github homepage" uuid="whatever-id" >}} (same UUID)
```
That's how we handle Resource Links. The display text is controlled via CKeditor + Shortcode parameters. The Resource's `WebsiteContent.title` property only affects the dedicated resource page at `/courses/course-name/resources/resource-name`. 

Note that this impacts the UX:
- if different links with the same URL are the same content object, then editing the URL changes the link everywhere.
    - imo this would be expected if the link URL is only editable by a dedicated page in Studio, but would be confusing if the link URL were editable by a custom CKEditor plugin. 
- editing link text in CKEditor may be more intuitive for authors, since it's the same experience as Resource Links.

2024-01-25 06:43 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +        help: Text to display as the link.
Thank you @ChristopherChudzicki! Using a param sounds a lot better.

2024-01-25 18:15 UTC, pdpinch requested changes
Some more comments, the most significant one being that we want to call these "External Resources" to make them sound more like existing resources and less like generic links.

2024-01-25 18:15 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +    label: Links
```suggestion
    name: external-resource
    label: External Resources
```

I don't care too much about the name, but we decided to call these "External Resources" because they're not just links. And they will behave like resources in every other way.

2024-01-25 18:15 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +    folder: content/links
Does this mean that when we download the course there will be a folder of links?

```suggestion
    folder: content/external-resources
```

2024-01-25 18:15 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +          embeds.
1. The Buy at Amazon links were supposed to be removed, so if you see any of those, they are data bugs. If you want to give me a list, I'll find someone to correct them all. 

2. The "Buy at MIT Press" link seems like it should be a CSS style instead of being embedded in the markdown. I'm not sure if this is feasible. Maybe something to discuss with Bilal. 

2. The "Student work from Angela" images don't seem to be working, so I'm not sure what that's supposed to be. 

In any case, this is only for legacy support and I think we should work to clean up the legacy content, instead of bending our metadata schema to match it. We can leave this out for now and give ourselves some time to work on the cleanup.

2024-01-25 18:15 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +        help: URL to use when is_broken is true.
What is the effect of putting this metadata into the project as opposed to some kind of separate admin table in studio? I'm not very certain at this time what's needed here, and since it's not author-editable, I think it could be completely separate.

2024-01-25 18:15 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
>              value: https://creativecommons.org/publicdomain/zero/1.0/
Should this be a separate PR? If you are going to include it here, you might as well add "All Rights Reserved"

I don't know if there is an appropriate URL for that.

2024-01-26 08:23 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +          embeds.
Sounds good. I'll remove this field.

2024-01-26 08:29 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +            value: externally-managed
I don't know if legal has a term for this. "Externally Managed" or maybe "External Licence" indicates that the license for this content is managed by an external entity.

This is a foresight to support https://github.com/mitodl/hq/issues/1812

2024-01-26 08:34 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +    folder: content/links
> Does this mean that when we download the course there will be a folder of links?

Yes.

2024-01-26 08:40 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
>              value: https://creativecommons.org/publicdomain/zero/1.0/
> Should this be a separate PR?

Good point. This PR might take some time to be released. I'll create a separate PR for this.

2024-01-26 09:22 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +        help: URL to use when is_broken is true.
It seems logically more coherent to me for the data related to the content to be inside the content. "What is the original content" and "Where is it backed up" are something I would expect to see inside the content objects.

More technically, right now they're two fields to avoid sharing the same field between the original and backup urls.

For example, let's say a user creates a link `https://example.com`. A few days later this link breaks and our system changes it to `https://archive.org/details/example.com`. Without the separate fields, when the author opens the link, he'll see the backup URL, which is not what he added.

So, I believe the final decision about where to move these fields depends on our desired UX. Is it okay for us to change something that the author explicitly added?

2024-01-26 13:55 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +            value: externally-managed
Oh, we should not overload the license field. Whether the site is "external" is different from it's license. 

Please add another field. I think "Externally Managed" is an OK label. If it's possible, the course authors prefer "Yes" and "No" options.

2024-01-26 17:07 UTC, gumaerc commented on ocw-course-v2/ocw-studio.yaml
> +    folder: content/links
To prevent rendering of content in Hugo's output, you can inject this into the front matter:

```yaml
_build:
  list: True
  render: False
```

`list` controls whether or not the content shows up during templating when iterating things like `site.Pages`, and `render` controls whether or not HTML (or any custom output formats) are generated during the build. This is a content level setting, so you can't control different behavior between online and offline themes but I don't think we need to render "resource pages" for links anyway, we just need the metadata.

2024-01-29 08:14 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +            value: externally-managed
> If it's possible, the course authors prefer "Yes" and "No" options.

Custom labels on a boolean field aren't possible without changes to Studio. However, if the UX is acceptable, we can make it a dropdown. The user can select "Yes" or "No" from the dropdown.

2024-01-29 09:51 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
>              value: https://creativecommons.org/publicdomain/zero/1.0/
https://github.com/mitodl/ocw-hugo-projects/pull/274

2024-01-29 14:39 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +        help: URL to use when is_broken is true.
Ok. I'd like to run this by @Ferdi and @gumaerc as well.

2024-01-29 14:47 UTC, gumaerc commented on ocw-course-v2/ocw-studio.yaml
> +        help: URL to use when is_broken is true.
I think with Internet Archive links specifically, it isn't that big of a deal because the original URL is included in the internet archive URL. When you visit the page on Internet Archive, it also shows the original URL at the top. If we were to implement Permatools, I'm not sure how that would change things. My main point is that although the internet archive does a good job of showing you the original URL, maybe that won't be what we use for archiving all the time, so we should account for that. It's easy to assume the Internet Archive will never go away (and I hope it doesn't) but anything is possible I suppose.

2024-01-31 19:26 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +          license.
I showed this to the OCW team today and they reminded me that we already had discussed this case, as part of https://github.com/mitodl/hq/issues/1812#issuecomment-1788850100

Can we implement the labels you proposed in that comment? Do we need to use a drop-down instead of radio buttons?

2024-02-01 11:44 UTC, HussainTaj-arbisoft commented on ocw-course-v2/ocw-studio.yaml
> +          license.
> Can we implement the labels you proposed in that comment?

In the [following comments](https://github.com/mitodl/hq/issues/1812#issuecomment-1816671623), they suggested some labels themselves. That looks like this 
<img width="539" alt="Screenshot 2024-02-01 at 4 36 22 PM" src="https://github.com/mitodl/ocw-hugo-projects/assets/71316217/19152a59-6aa8-4c3b-b76c-d8361e68bf9e">

Does this work? We can't add "Yes"  or "No" options, as they suggested.


> Do we need to use a drop-down instead of radio buttons?

No. We should avoid that if possible. I suggested that as an option when we can neither use "True/False" labels nor update Studio components.

2024-02-02 12:09 UTC, HussainTaj-arbisoft commented
@pdpinch here are some new screenshots. Let me know if you need screenshots of any other UI.

<img width="1792" alt="Screenshot 2024-02-02 at 4 54 51 PM" src="https://github.com/mitodl/ocw-hugo-projects/assets/71316217/b7fc66b7-fc54-4d59-aafd-a70be28e80b9">

<img width="1792" alt="Screenshot 2024-02-02 at 4 55 13 PM" src="https://github.com/mitodl/ocw-hugo-projects/assets/71316217/2253dc24-620e-448b-8fe1-53d2c8a4aae4">

<img width="1792" alt="Screenshot 2024-02-02 at 4 55 25 PM" src="https://github.com/mitodl/ocw-hugo-projects/assets/71316217/5e868e72-6600-48b3-be80-1c1f16963aca">

<img width="1792" alt="Screenshot 2024-02-02 at 5 03 33 PM" src="https://github.com/mitodl/ocw-hugo-projects/assets/71316217/ed3cf774-6727-43d7-ae79-43d6bf567933">


<img width="1792" alt="Screenshot 2024-02-02 at 4 55 47 PM" src="https://github.com/mitodl/ocw-hugo-projects/assets/71316217/ae76cb81-6015-4564-bcb5-0000389059b0">

---

I found that the "open content is new tab" thing doesn't work for these new external resources. I'll look into if there is a config requirement for it or if Studio needs an update.


<img width="462" alt="Screenshot 2024-02-02 at 4 57 45 PM" src="https://github.com/mitodl/ocw-hugo-projects/assets/71316217/19128603-5415-4222-ab0d-51dc88a817d7">

2024-02-20 17:49 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +          You can change this later when adding links.
Since we're reconsidering how to add links, let's remove this help text for now.

2024-02-20 18:47 UTC, pdpinch commented on ocw-course-v2/ocw-studio.yaml
> +          or https://owl.english.purdue.edu/owl/resource/747/01/
```suggestion
        help: >
          The URL. For example, https://owl.english.purdue.edu/owl/resource/747/01/
```

on example is enough

2024-02-20 18:49 UTC, pdpinch approved these changes
@HussainTaj-arbisoft I left you two, last comments on this. You can merge after you make those changes.

2024-02-26 13:23 UTC, HussainTaj-arbisoft commented
This PR will be merged with https://github.com/mitodl/ocw-hugo-themes/pull/1298.

2024-02-26 23:22 UTC, gumaerc commented
Ignore my accidental reassigning of the issue above, but I approved https://github.com/mitodl/ocw-hugo-themes/pull/1298. This can be merged and released after the themes PR release is complete.

2024-02-27 18:19 UTC, pdpinch commented
After this is merged, the OCW team would like to review it on RC/QA before it goes live.

2024-02-29 06:33 UTC, merged