Added nav menu to site config
mitodl/ocw-hugo-projects pull request #33
Opened 2021-07-23 18:06 UTC by gsidebo

#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
N/A

#### What's this PR do?
Adds a nav menu to the site config so that published course sites can have a Hugo menu configured

#### How should this be manually tested?
- Convert `ocw-course/ocw-studio.yaml` to JSON and paste it into a new Website Starter in your local instance of `ocw-studio` (or on RC).
- Create a Website using this new Website Starter, and create a few pages. 
- Go to settings > menu, add those pages and some external links to the menu, and save. A WebsiteContent record should be created with a Hugo-compatible menu format saved for the "metadata" field

2021-07-26 18:58 UTC, gumaerc requested changes
I have some concerns about Hugo specific things with this implementation:

2021-07-26 18:58 UTC, gumaerc commented on ocw-www/ocw-studio.yaml
> +      - file: config/menu-sidenav.yml
Unfortunately, in order for this to work with Hugo all menus must be in a file called `menus.yaml`.  More info on that here:

https://gohugo.io/getting-started/configuration/#configuration-directory

You might notice that you can create separate menu config files for different languages, but it's really designed only to be used for different language codes.  I've experimented with this and if you create a menu file that doesn't match a configured language then Hugo will throw an error at build time.  For instance, I tried creating a `menus.leftnav.yaml` file and then Hugo complained that a menu for `en` (the configured language code) doesn't exist.  So we will have to use the one `menus.yaml` file, then the way we separate different menus are with the root key in this file.  Here is what was created after I tested this:

```
menu:
  mainmenu:
  - identifier: bc941918-fe95-4c4a-8269-87a56bb93076
    name: Test Document
    url: content/resources/test-document.md
    weight: 0
 ```

In the `menus.yaml` file, the `menu` key is not necessary.  This is how it should look:

```
mainmenu:
- identifier: bc941918-fe95-4c4a-8269-87a56bb93076
  name: Test Document
  url: content/resources/test-document.md
  weight: 0
```

2021-07-26 21:18 UTC, gumaerc commented on ocw-www/ocw-studio.yaml
> +      - file: config/menu-sidenav.yml
To clarify, the file these need to go in should be stored at `config/_default/menus.yaml`.  I made an issue for the root level key problem in `ocw-studio` here: https://github.com/mitodl/ocw-studio/issues/416

2021-07-28 21:35 UTC, gsidebo commented
@gumaerc The root issue has been fixed (https://github.com/mitodl/ocw-studio/pull/425), and I updated the config in this PR

2021-07-28 22:36 UTC, gumaerc approved these changes
:+1:

2021-07-29 03:12 UTC, merged