various updates to the configuration to fix some issues and add missi…
mitodl/ocw-hugo-projects pull request #6
Opened 2021-06-15 18:56 UTC by gumaerc

#### Pre-Flight checklist

- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Fixes https://github.com/mitodl/ocw-hugo-projects/issues/5

#### What's this PR do?
This PR fixes a number of issues:
 - `name` property on collection items set to plurals to match `ocw-hugo-themes` so the `type` key is written out properly
 - `lead_quote` corrected to `leadquote`
 - `image_object` wrappers removed, as they create the object structure in the resulting front matter
 - `body` added to notifications
 - `subtitle` added to promos

#### How should this be manually tested?
- Create a new `WebsiteStarter` in `ocw-studio` RC Django admin
- Convert `ocw-www/ocw-studio.yaml` to JSON and paste it in the Config field for the starter
- Create a new `Website` using this starter
- Create one of each type of content, then hit the preview button
- Find the site's repo on https://github.mit.edu and look through the markdown
- Verify:
 - The `type` properties in the front matter of the various pieces of content are plural and match it's designated type in `ocw-hugo-themes/www/layouts/`
 - There are no `image_object` wrappers written into the front matter of any content
 - The newly added fields appear where they should
 - `lead_quote` in testimonials is now `leadquote`

2021-06-15 19:50 UTC, Ferdi commented on ocw-www/ocw-studio.yaml
> +        widget: markdown
This should be "minimal"?
- {label: "Body", name: "body", widget: "markdown", minimal="true"}

2021-06-16 16:05 UTC, mbertrand reviewed
Overall looks great.

2021-06-16 18:06 UTC, mbertrand requested changes

2021-06-16 18:06 UTC, mbertrand commented on ocw-www/ocw-studio.yaml
>          widget: string
Now that [this PR](https://github.com/mitodl/ocw-studio/pull/305) is merged, I think a `required: true` line will be needed for any `title` fields added here, in order to pass validation in ocw-studio.

2021-06-16 21:49 UTC, gumaerc commented
@mbertrand I made some changes based on your feedback above and this is ready for another look but I want to pose a question:

Now that images have been added as a resource here and the image fields in promos and testimonials are relation fields, should we move `image_alt` to the image resource?  I think it makes the most sense for the alt text to be stored on the image resource itself.  It will require a theme change, but I think it's the right thing to do.  @Ferdi what do you think?

2021-06-17 12:22 UTC, mbertrand commented
Moving `image_alt` to the image resource sounds good to me

2021-06-17 12:32 UTC, mbertrand commented on ocw-www/ocw-studio.yaml
> +    folder: content
Put it in a subfolder maybe?

2021-06-17 12:33 UTC, mbertrand reviewed
Works great, just one suggestion about the resource folder

2021-06-17 16:22 UTC, gumaerc commented
@mbertrand I reverted the image relation widget code for now, that will come in a separate PR

2021-06-17 17:03 UTC, mbertrand approved these changes
👍

2021-06-17 17:17 UTC, merged